name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: cd libctrpf
      run: cd ${{github.workspace}}/libctrpf/Library
    - name: make libctrpf
      run: make
    - name: cd root
      run: cd ${{github.workspace}}
    - name: make root
      run: make
      
      
