name: C/C++ CI

on:
  push:
    # ignore paths that don't affect this workflow
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '**.bat'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: make libctrpf
      working-directory: ${{github.workspace}}/libctrpf/Library
      run: make
    - name: make plugin
      working-directory: ${{github.workspace}}
      run: |
           chmod +x 3gxtool
           cp 3gxtool /opt/devkitpro/tools/bin/
           make

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: |
              Vapecord-ACNL-Plugin.elf
              Vapecord-ACNL-Plugin.3gx
